platform :ios, '6.0'
pod 'Reachability'
pod 'SBJson'
pod 'SDWebImage'
pod 'DTCoreText'
pod 'STableViewController'
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'Mantle'
pod 'Godzippa'
pod 'EGOCache'
pod 'SecureUDID'
pod 'MJRefresh'
#pod 'MWPhotoBrowser'